export { ColumnsBlockConfig } from '@/_components/blocks/Columns'
export { CTABlockConfig } from '@/_components/blocks/CTA'
export { RichTextConfig } from '@/_components/blocks/RichText'
export { VideoPlayerBlockConfig } from '@/_components/blocks/VideoPlayer'
export { DynamicTextInlineBlockConfig } from '@/_components/inlineBlocks/DynamicText'
