export const COUNTRY_LANGUAGES = {
  ENG: 'English',
  ARA: 'Arabic',
  CAT: 'Catalan',
  VIE: 'Vietnamese',
  SPA: 'Spanish',
  HEB: 'Hebrew',
  MYA: 'Burmese',
  POL: 'Polish',
  PRS: 'Dari',
  PUS: 'Pashto',
  TUK: 'Turkmen',
  SWA: 'Swahili',
  POR: 'Portuguese',
  DZO: 'Dzongkha',
  MLT: 'Maltese',
  RUS: 'Russian',
  NEP: 'Nepali',
  POV: 'Upper Guinea Creole',
  ARC: 'Aramaic',
  CKB: 'Sorani',
  FRA: 'French',
  AFR: 'Afrikaans',
  NBL: 'Southern Ndebele',
  NSO: 'Northern Sotho',
  SOT: 'Sotho',
  SSW: 'Swazi',
  TSN: 'Tswana',
  TSO: 'Tsonga',
  VEN: 'Venda',
  XHO: 'Xhosa',
  ZUL: 'Zulu',
  DEU: 'German',
  RUN: 'Kirundi',
  KIN: 'Kinyarwanda',
  NLD: 'Dutch',
  MAH: 'Marshallese',
  EUS: 'Basque',
  GLC: 'Galician',
  KIR: 'Kyrgyz',
  SMO: 'Samoan',
  NYA: 'Chewa',
  THA: 'Thai',
  TUR: 'Turkish',
  FIL: 'Filipino',
  SLV: 'Slovene',
  KAT: 'Georgian',
  ELL: 'Greek',
  HYE: 'Armenian',
  GIL: 'Gilbertese',
  FAS: 'Persian (Farsi)',
  MON: 'Mongolian',
  RON: 'Romanian',
  MRI: 'Māori',
  NZS: 'New Zealand Sign Language',
  SOM: 'Somali',
  HIN: 'Hindi',
  TAM: 'Tamil',
  KON: 'Kikongo',
  LIN: 'Lingala',
  LUA: 'Tshiluba',
  KOR: 'Korean',
  DIV: 'Maldivian',
  SRP: 'Serbian',
  LAO: 'Lao',
  FIN: 'Finnish',
  SWE: 'Swedish',
  BWG: 'Chibarwe',
  KCK: 'Kalanga',
  KHI: 'Khoisan',
  NDC: 'Ndau',
  NDE: 'Northern Ndebele',
  SNA: 'Shona',
  TOI: 'Tonga',
  ZIB: 'Zimbabwean Sign Language',
  AYM: 'Aymara',
  GRN: 'Guaraní',
  QUE: 'Quechua',
  HUN: 'Hungarian',
  NNO: 'Norwegian Nynorsk',
  NOB: 'Norwegian Bokmål',
  SMI: 'Sami',
  LIT: 'Lithuanian',
  MFE: 'Mauritian Creole',
  SLK: 'Slovak',
  TVL: 'Tuvaluan',
  KAL: 'Greenlandic',
  UZB: 'Uzbek',
  BEN: 'Bengali',
  ZHO: 'Chinese',
  ITA: 'Italian',
  EST: 'Estonian',
  KHM: 'Khmer',
  KAZ: 'Kazakh',
  IND: 'Indonesian',
  LTZ: 'Luxembourgish',
  BER: 'Berber',
  MEY: 'Hassaniya',
  ZDJ: 'Comorian',
  BUL: 'Bulgarian',
  AMH: 'Amharic',
  TGK: 'Tajik',
  SQI: 'Albanian',
  BIS: 'Bislama',
  MSA: 'Malay',
  DAN: 'Danish',
  CRS: 'Seychellois Creole',
  UKR: 'Ukrainian',
  LAV: 'Latvian',
  TIR: 'Tigrinya',
  HRV: 'Croatian',
  HMO: 'Hiri Motu',
  TPI: 'Tok Pisin',
  PAU: 'Palauan',
  BOS: 'Bosnian',
  CNR: 'Montenegrin',
  URD: 'Urdu',
  MLG: 'Malagasy',
  AZE: 'Azerbaijani',
  SAG: 'Sango',
  MKD: 'Macedonian',
  HER: 'Herero',
  HGM: 'Khoekhoe',
  KWN: 'Kwangali',
  LOZ: 'Lozi',
  NDO: 'Ndonga',
  GLE: 'Irish',
  GSW: 'Swiss German',
  ROH: 'Romansh',
  CES: 'Czech',
  ISL: 'Icelandic',
  JPN: 'Japanese',
  BJZ: 'Belizean Creole',
  BEL: 'Belarusian',
  TET: 'Tetum',
  HAT: 'Haitian Creole',
  RAR: 'Cook Islands Māori',
  SIN: 'Sinhala',
  TON: 'Tongan',
  FIJ: 'Fijian',
  HIF: 'Fiji Hindi',
  JAM: 'Jamaican Patois',
  PTBR: 'Brazilian Portuguese',
} as const
