import {
  CBFieldBlock,
  CBGroupFieldBlock,
  CountryFieldBlock,
  EmailFieldBlock,
  MessageFieldBlock,
  NumberFieldBlock,
  PronounsFieldBlock,
  RadioFieldBlock,
  SelectFieldBlock,
  SignatureFieldBlock,
  StateFieldBlock,
  TextareaFieldBlock,
  TextFieldBlock,
  TimezoneFieldBlock,
  UploadFieldBlock,
} from '@/_components/blocks/Form/FieldBlocks'

export const BASE_FIELDS = [
  CBFieldBlock,
  CBGroupFieldBlock,
  CountryFieldBlock,
  EmailFieldBlock,
  MessageFieldBlock,
  NumberFieldBlock,
  PronounsFieldBlock,
  RadioFieldBlock,
  SelectFieldBlock,
  SignatureFieldBlock,
  StateFieldBlock,
  TextareaFieldBlock,
  TextFieldBlock,
  TimezoneFieldBlock,
  UploadFieldBlock,
]
