import {
  type LucideIcon,
  Award,
  BadgeCheck,
  BookOpen,
  Building2,
  Church,
  Coins,
  Globe,
  GraduationCap,
  HandCoins,
  Handshake,
  Heart,
  HeartHandshake,
  Home,
  Landmark,
  Leaf,
  Megaphone,
  MessageCircle,
  Scale,
  Shield,
  Smile,
  Star,
  Sun,
} from 'lucide-react'

export const BTN_SIZE = 16

export const QUICK_ICONS: Array<{ id: string; label: string; Comp: LucideIcon }> = [
  { id: 'Heart', label: 'Heart', Comp: Heart },
  { id: 'HeartHandshake', label: 'Heartshake', Comp: HeartHandshake },
  { id: 'Handshake', label: 'Handshake', Comp: Handshake },
  { id: 'Shield', label: 'Shield', Comp: Shield },
  { id: 'Star', label: 'Star', Comp: Star },
  { id: 'Globe', label: 'Globe', Comp: Globe },
  { id: 'Home', label: 'Home', Comp: Home },
  { id: 'Building2', label: 'Building', Comp: Building2 },
  { id: 'Landmark', label: 'Landmark', Comp: Landmark },
  { id: 'Church', label: 'Church', Comp: Church },
  { id: 'Scale', label: 'Scale', Comp: Scale },
  { id: 'Award', label: 'Award', Comp: Award },
  { id: 'BadgeCheck', label: 'Badge', Comp: BadgeCheck },
  { id: 'Megaphone', label: 'Megaphone', Comp: Megaphone },
  { id: 'MessageCircle', label: 'Message', Comp: MessageCircle },
  { id: 'BookOpen', label: 'Book', Comp: BookOpen },
  { id: 'GraduationCap', label: 'Education', Comp: GraduationCap },
  { id: 'Coins', label: 'Coins', Comp: Coins },
  { id: 'HandCoins', label: 'HandCoins', Comp: HandCoins },
  { id: 'Leaf', label: 'Leaf', Comp: Leaf },
  { id: 'Sun', label: 'Sun', Comp: Sun },
  { id: 'Smile', label: 'Smile', Comp: Smile },
]

export const SPECIAL_ICONS = [
  { id: 'pride', label: 'Pride Flag' },
  { id: 'trans', label: 'Trans Flag' },
  { id: 'un', label: 'UN' },
  { id: 'blm', label: 'Black Power' },
] as const
